#DECISION TREE FROM SCRATCH 

def entropy(y): ...
    # -sum(p * log2(p)) for each class

def information_gain(X_col, y, threshold): ...
    # entropy(parent) - weighted_avg(entropy(left), entropy(right))

def best_split(X, y): ...
    # iterate all features + candidate thresholds, return best (feature, threshold)

class Node:
    def __init__(self, feature=None, threshold=None, left=None, right=None, value=None): ...

class DecisionTree:
    def __init__(self, max_depth=20, min_samples_split=2): ...

    def fit(self, X, y): ...
        # recursive _build_tree()

    def _build_tree(self, X, y, depth): ...
        # base cases: pure node, max_depth, min_samples
        # else: best_split → split → recurse left/right

    def predict(self, X): ...
        # traverse tree for each sample

    def predict_proba(self, X): ...
        # return class distribution at leaf (needed for GA fitness)

    def save(self, path): ...   # pickle
    def load(self, path): ...